repos:
  - repo: https://github.com/mvdan/gofumpt
    rev: v0.8.0
    hooks:
      - id: gofumpt
        args: ["-extra"] # строже, чем gofmt

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint
        args: ["--timeout=5m"]
