repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.1.6
    hooks:
      - id: golangci-lint
        files: '^(services/[^/]+/.*\.go)$'
        pass_filenames: false
        args:
          - --timeout=5m
          - services/auth-svc/...
          - services/budget-svc/...
          - services/expense-svc/...
          - services/gateway-svc/...
          - services/notification-svc/...
          - services/obsidian-sync-svc/...
          - services/profile-svc/...