global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files: []

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node exporter (если будет добавлен)
  - job_name: 'node'
    static_configs:
      - targets: []

  # Go приложения (будут добавлены позже)
  - job_name: 'go-services'
    static_configs:
      - targets: []
