name: build-and-test

on:
  push:
  pull_request:

jobs:
  test:
    name: build-and-test / test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth-svc
          - budget-svc
          - expense-svc
          - gateway-svc
          - notification-svc
          - obsidian-sync-svc
          - profile-svc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6

      - name: Lint ${{ matrix.service }}
        run: |
          cd services/${{ matrix.service }}
          $(go env GOPATH)/bin/golangci-lint run --timeout=5m ./...

      - name: Test ${{ matrix.service }}
        run: |
          cd services/${{ matrix.service }}
          go test ./...